export type CatalogModelStatus =
  | "active"
  | "deprecated"
  | "retired"
  | "hosted"
  | "legacy";

export interface CuratedModel {
  name: string;
  provider: string;
  apiId?: string;
  aliases: readonly string[];
  contextWindow: number | null;
  costInputPer1M: number | null;
  costOutputPer1M: number | null;
  status: CatalogModelStatus;
  notes: string;
  sourceUrls: readonly string[];
  lastVerified: string;
}

export interface CatalogModelOption {
  name: string;
  provider: string;
  contextWindow: number | null;
  costInputPer1M: number | null;
  costOutputPer1M: number | null;
  hasBenchmarks: boolean;
  status: CatalogModelStatus | "benchmarked";
  sourceUrls?: readonly string[];
  lastVerified?: string;
}

type BenchmarkMetadataRecord = {
  modelName: string;
  provider: string;
  contextWindow?: number | null;
  costInputPer1M?: number | null;
  costOutputPer1M?: number | null;
};

type DbCatalogModel = {
  name: string;
  provider: string;
  contextWindow?: number | null;
  costInputPer1M?: number | null;
  costOutputPer1M?: number | null;
  scores?: readonly unknown[] | null;
};

const LAST_VERIFIED = "2026-05-04";

const SOURCES = {
  anthropic: [
    "https://platform.claude.com/docs/en/about-claude/pricing",
    "https://platform.claude.com/docs/en/about-claude/models/overview",
    "https://platform.claude.com/docs/en/about-claude/model-deprecations",
  ],
  google: [
    "https://ai.google.dev/gemini-api/docs/pricing",
    "https://ai.google.dev/gemini-api/docs/models",
    "https://cloud.google.com/vertex-ai/generative-ai/pricing",
  ],
  deepseek: ["https://api-docs.deepseek.com/quick_start/pricing/"],
  kimi: [
    "https://platform.kimi.ai/docs/models",
    "https://platform.kimi.ai/docs/pricing/chat",
    "https://platform.kimi.ai/docs/pricing/chat-k26",
    "https://platform.kimi.ai/docs/pricing/chat-k25",
    "https://platform.kimi.ai/docs/pricing/chat-k2",
  ],
  qwen: [
    "https://www.alibabacloud.com/help/en/model-studio/models",
    "https://www.alibabacloud.com/help/en/model-studio/model-pricing",
  ],
  zai: [
    "https://docs.z.ai/guides/overview/pricing",
    "https://docs.z.ai/guides/llm/glm-5.1",
    "https://docs.z.ai/guides/llm/glm-5",
    "https://docs.z.ai/guides/llm/glm-4.7",
    "https://docs.z.ai/guides/llm/glm-4.6",
    "https://docs.z.ai/guides/llm/glm-4.5",
  ],
  mistral: [
    "https://docs.mistral.ai/models/model-cards/mistral-medium-3-1-25-08",
    "https://docs.mistral.ai/models/model-cards/mistral-small-3-2-25-06",
    "https://docs.mistral.ai/models/model-cards/ministral-3-8b-25-12",
  ],
  cohere: [
    "https://docs.cohere.com/docs/command-a",
    "https://docs.cohere.com/v1/docs/command-r7b",
    "https://docs.cohere.com/docs/command-r",
    "https://docs.cohere.com/docs/command-r-plus",
  ],
  ai21: [
    "https://www.ai21.com/pricing/",
    "https://docs.ai21.com/docs/jamba-foundation-models",
  ],
  groq: [
    "https://groq.com/pricing",
    "https://console.groq.com/docs/model/llama-3.1-8b-instant",
  ],
  openai: [
    "https://openai.com/api/pricing/",
    "https://developers.openai.com/api/docs/models",
  ],
  xai: ["https://docs.x.ai/developers/models?cluster=us-west-1"],
} as const;

export const CURATED_MODEL_CATALOG = [
  {
    name: "Claude Opus 4.7",
    provider: "Anthropic",
    apiId: "claude-opus-4-7",
    aliases: ["claude-opus-4.7", "opus-4.7"],
    contextWindow: 1_000_000,
    costInputPer1M: 5,
    costOutputPer1M: 25,
    status: "active",
    notes: "Current Claude Opus family entry; base token pricing excludes caching, batch, data residency, fast mode, and tools.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude Opus 4.6",
    provider: "Anthropic",
    apiId: "claude-opus-4-6",
    aliases: ["claude-opus-4.6", "opus-4.6"],
    contextWindow: 1_000_000,
    costInputPer1M: 5,
    costOutputPer1M: 25,
    status: "active",
    notes: "Current Claude Opus row with 1M context at standard pricing.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude Opus 4.5",
    provider: "Anthropic",
    apiId: "claude-opus-4-5-20251101",
    aliases: ["claude-opus-4-5", "claude-opus-4.5"],
    contextWindow: 200_000,
    costInputPer1M: 5,
    costOutputPer1M: 25,
    status: "active",
    notes: "Current Claude Opus 4.5 row with standard base pricing.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude Opus 4.1",
    provider: "Anthropic",
    apiId: "claude-opus-4-1-20250805",
    aliases: ["claude-opus-4-1", "claude-opus-4.1"],
    contextWindow: 200_000,
    costInputPer1M: 15,
    costOutputPer1M: 75,
    status: "active",
    notes: "Older Opus 4.x row retained for comparisons and benchmark aliases.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude Opus 4",
    provider: "Anthropic",
    apiId: "claude-opus-4-20250514",
    aliases: ["claude-opus-4", "claude-opus-4.0"],
    contextWindow: 200_000,
    costInputPer1M: 15,
    costOutputPer1M: 75,
    status: "deprecated",
    notes: "Deprecated Opus 4 row retained for older benchmark and user-selected comparisons.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    apiId: "claude-sonnet-4-6",
    aliases: ["claude-sonnet-4.6", "sonnet-4.6", "claude-4.6-sonnet"],
    contextWindow: 1_000_000,
    costInputPer1M: 3,
    costOutputPer1M: 15,
    status: "active",
    notes: "Current Claude Sonnet row with standard base token pricing.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude Sonnet 4.5",
    provider: "Anthropic",
    apiId: "claude-sonnet-4-5-20250929",
    aliases: ["claude-sonnet-4-5", "claude-sonnet-4.5"],
    contextWindow: 200_000,
    costInputPer1M: 3,
    costOutputPer1M: 15,
    status: "active",
    notes: "Claude Sonnet 4.5 row with standard base token pricing.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude Sonnet 4",
    provider: "Anthropic",
    apiId: "claude-sonnet-4-20250514",
    aliases: ["claude-sonnet-4", "claude-sonnet-4.0"],
    contextWindow: 200_000,
    costInputPer1M: 3,
    costOutputPer1M: 15,
    status: "deprecated",
    notes: "Deprecated Sonnet 4 row retained for still-used integrations.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude Haiku 4.5",
    provider: "Anthropic",
    apiId: "claude-haiku-4-5",
    aliases: ["claude-haiku-4.5", "haiku-4.5"],
    contextWindow: 200_000,
    costInputPer1M: 1,
    costOutputPer1M: 5,
    status: "active",
    notes: "Low-cost Claude family baseline.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude Sonnet 3.7",
    provider: "Anthropic",
    apiId: "claude-3-7-sonnet-20250219",
    aliases: ["claude-3.7-sonnet", "claude-3-7-sonnet"],
    contextWindow: 200_000,
    costInputPer1M: 3,
    costOutputPer1M: 15,
    status: "retired",
    notes: "Older Sonnet row retained for historical comparisons.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    apiId: "claude-3-5-sonnet",
    aliases: ["claude-3.5-sonnet", "claude-3-5-sonnet-20241022"],
    contextWindow: 200_000,
    costInputPer1M: 3,
    costOutputPer1M: 15,
    status: "legacy",
    notes: "Popular older Sonnet baseline kept for benchmark matching.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude 3.5 Haiku",
    provider: "Anthropic",
    apiId: "claude-3-5-haiku-20241022",
    aliases: ["claude-3.5-haiku", "claude-3-5-haiku"],
    contextWindow: 200_000,
    costInputPer1M: 0.8,
    costOutputPer1M: 4,
    status: "retired",
    notes: "Older low-cost Claude row retained for comparison.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude 3 Opus",
    provider: "Anthropic",
    apiId: "claude-3-opus-20240229",
    aliases: ["claude-3-opus", "claude-opus-3"],
    contextWindow: 200_000,
    costInputPer1M: 15,
    costOutputPer1M: 75,
    status: "retired",
    notes: "Retired Claude Opus 3 row kept for still-used benchmark labels.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude 3 Haiku",
    provider: "Anthropic",
    apiId: "claude-3-haiku-20240307",
    aliases: ["claude-3-haiku", "claude-haiku-3"],
    contextWindow: 200_000,
    costInputPer1M: 0.25,
    costOutputPer1M: 1.25,
    status: "retired",
    notes: "Retired Claude Haiku 3 row kept for still-used benchmark labels.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Claude 3 Sonnet",
    provider: "Anthropic",
    apiId: "claude-3-sonnet-20240229",
    aliases: ["claude-3-sonnet", "claude-sonnet-3"],
    contextWindow: 200_000,
    costInputPer1M: 3,
    costOutputPer1M: 15,
    status: "retired",
    notes: "Retired Claude Sonnet 3 row kept for historical comparisons.",
    sourceUrls: SOURCES.anthropic,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 3.1 Pro Preview",
    provider: "Google",
    apiId: "gemini-3.1-pro-preview",
    aliases: ["gemini-3.1-pro-preview", "gemini-3-1-pro-preview"],
    contextWindow: 1_048_576,
    costInputPer1M: 2,
    costOutputPer1M: 12,
    status: "active",
    notes: "Preview Gemini 3.1 Pro standard pricing uses the <=200k prompt tier.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 3.1 Flash-Lite Preview",
    provider: "Google",
    apiId: "gemini-3.1-flash-lite-preview",
    aliases: ["gemini-3-1-flash-lite-preview"],
    contextWindow: 1_048_576,
    costInputPer1M: 0.25,
    costOutputPer1M: 1.5,
    status: "active",
    notes: "Preview Gemini 3.1 Flash-Lite standard text/image/video pricing.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 2.5 Pro",
    provider: "Google",
    apiId: "gemini-2.5-pro",
    aliases: ["gemini-2-5-pro", "gemini-2.5-pro-preview"],
    contextWindow: 1_048_576,
    costInputPer1M: 1.25,
    costOutputPer1M: 10,
    status: "active",
    notes: "Gemini API pricing uses the lowest standard prompt-length tier.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 2.5 Flash",
    provider: "Google",
    apiId: "gemini-2.5-flash",
    aliases: ["gemini-2-5-flash", "gemini-flash-2.5"],
    contextWindow: 1_048_576,
    costInputPer1M: 0.3,
    costOutputPer1M: 2.5,
    status: "active",
    notes: "Gemini API pricing uses standard non-cache token prices.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 2.5 Flash-Lite",
    provider: "Google",
    apiId: "gemini-2.5-flash-lite",
    aliases: ["gemini-2-5-flash-lite"],
    contextWindow: 1_048_576,
    costInputPer1M: 0.1,
    costOutputPer1M: 0.4,
    status: "active",
    notes: "Budget Gemini 2.5 row with standard text/image/video pricing.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 2.0 Flash",
    provider: "Google",
    apiId: "gemini-2.0-flash",
    aliases: ["gemini-2-0-flash"],
    contextWindow: 1_048_576,
    costInputPer1M: 0.1,
    costOutputPer1M: 0.4,
    status: "active",
    notes: "Low-cost Gemini 2.0 baseline.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 2.0 Flash-Lite",
    provider: "Google",
    apiId: "gemini-2.0-flash-lite",
    aliases: ["gemini-2-0-flash-lite"],
    contextWindow: 1_048_576,
    costInputPer1M: 0.075,
    costOutputPer1M: 0.3,
    status: "deprecated",
    notes: "Deprecated Gemini 2.0 Flash-Lite row kept for older comparisons.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 1.5 Pro",
    provider: "Google",
    apiId: "gemini-1.5-pro",
    aliases: ["gemini-1-5-pro"],
    contextWindow: 2_097_152,
    costInputPer1M: 1.25,
    costOutputPer1M: 5,
    status: "legacy",
    notes: "Older long-context Gemini row retained for comparisons.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 1.5 Flash",
    provider: "Google",
    apiId: "gemini-1.5-flash",
    aliases: ["gemini-1-5-flash"],
    contextWindow: 1_048_576,
    costInputPer1M: 0.075,
    costOutputPer1M: 0.3,
    status: "legacy",
    notes: "Legacy Gemini Flash row retained for older usage and benchmark labels.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 1.5 Flash-8B",
    provider: "Google",
    apiId: "gemini-1.5-flash-8b",
    aliases: ["gemini-1-5-flash-8b"],
    contextWindow: 1_048_576,
    costInputPer1M: 0.0375,
    costOutputPer1M: 0.15,
    status: "legacy",
    notes: "Older small Gemini Flash row retained for low-cost comparisons.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Gemini 1.0 Pro",
    provider: "Google",
    apiId: "gemini-1.0-pro-002",
    aliases: ["gemini-1.0-pro", "gemini-1-0-pro"],
    contextWindow: 32_000,
    costInputPer1M: 0.5,
    costOutputPer1M: 1.5,
    status: "retired",
    notes: "Retired Gemini 1.0 Pro row retained for historical comparisons.",
    sourceUrls: SOURCES.google,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Kimi K2.6",
    provider: "Moonshot AI",
    apiId: "kimi-k2.6",
    aliases: ["kimi-k2-6", "moonshot-kimi-k2.6"],
    contextWindow: 262_144,
    costInputPer1M: 0.95,
    costOutputPer1M: 4,
    status: "active",
    notes: "Kimi K2.6 chat pricing; provider docs include K2 family-specific pricing pages.",
    sourceUrls: SOURCES.kimi,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Kimi K2.5",
    provider: "Moonshot AI",
    apiId: "kimi-k2.5",
    aliases: ["kimi-k2-5"],
    contextWindow: 262_144,
    costInputPer1M: 0.6,
    costOutputPer1M: 3,
    status: "active",
    notes: "Kimi K2.5 chat pricing row.",
    sourceUrls: SOURCES.kimi,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Kimi K2 0905",
    provider: "Moonshot AI",
    apiId: "kimi-k2-0905-preview",
    aliases: ["kimi-k2", "kimi-k2-0905"],
    contextWindow: 262_144,
    costInputPer1M: 0.6,
    costOutputPer1M: 2.5,
    status: "deprecated",
    notes: "Kimi K2 series row kept until the documented May 25, 2026 discontinuation.",
    sourceUrls: SOURCES.kimi,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Kimi K2 0711",
    provider: "Moonshot AI",
    apiId: "kimi-k2-0711-preview",
    aliases: ["kimi-k2-0711"],
    contextWindow: 131_072,
    costInputPer1M: 0.6,
    costOutputPer1M: 2.5,
    status: "legacy",
    notes: "Older Kimi K2 preview row retained for still-used preview integrations.",
    sourceUrls: SOURCES.kimi,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Moonshot V1 8K",
    provider: "Moonshot AI",
    apiId: "moonshot-v1-8k",
    aliases: ["moonshot-v1-8192"],
    contextWindow: 8_192,
    costInputPer1M: 0.293,
    costOutputPer1M: 1.464,
    status: "legacy",
    notes: "Moonshot V1 CNY pricing converted to USD using the documented 2026-05-04 FX assumption.",
    sourceUrls: SOURCES.kimi,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Moonshot V1 32K",
    provider: "Moonshot AI",
    apiId: "moonshot-v1-32k",
    aliases: ["moonshot-v1-32768"],
    contextWindow: 32_768,
    costInputPer1M: 0.732,
    costOutputPer1M: 2.928,
    status: "legacy",
    notes: "Moonshot V1 CNY pricing converted to USD using the documented 2026-05-04 FX assumption.",
    sourceUrls: SOURCES.kimi,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Moonshot V1 128K",
    provider: "Moonshot AI",
    apiId: "moonshot-v1-128k",
    aliases: ["moonshot-v1-128000"],
    contextWindow: 128_000,
    costInputPer1M: 1.464,
    costOutputPer1M: 4.392,
    status: "legacy",
    notes: "Moonshot V1 CNY pricing converted to USD using the documented 2026-05-04 FX assumption.",
    sourceUrls: SOURCES.kimi,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "DeepSeek V4 Pro",
    provider: "DeepSeek",
    apiId: "deepseek-v4-pro",
    aliases: ["deepseek-v4-pro-20260426", "deepseek-pro-v4"],
    contextWindow: 1_000_000,
    costInputPer1M: 0.435,
    costOutputPer1M: 0.87,
    status: "active",
    notes: "Current discounted DeepSeek V4 Pro price shown on the official pricing page; list price is higher.",
    sourceUrls: SOURCES.deepseek,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "DeepSeek V4 Flash",
    provider: "DeepSeek",
    apiId: "deepseek-v4-flash",
    aliases: ["deepseek-flash-v4"],
    contextWindow: 1_000_000,
    costInputPer1M: 0.14,
    costOutputPer1M: 0.28,
    status: "active",
    notes: "Current DeepSeek V4 Flash row.",
    sourceUrls: SOURCES.deepseek,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "DeepSeek V3.2 Chat",
    provider: "DeepSeek",
    apiId: "deepseek-chat",
    aliases: ["deepseek-v3.2-chat", "deepseek-v3-2-chat"],
    contextWindow: 128_000,
    costInputPer1M: 0.28,
    costOutputPer1M: 0.42,
    status: "legacy",
    notes: "DeepSeek chat mode row retained because the API id is still common in integrations.",
    sourceUrls: SOURCES.deepseek,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "DeepSeek V3.2 Reasoner",
    provider: "DeepSeek",
    apiId: "deepseek-reasoner",
    aliases: ["deepseek-v3.2-reasoner", "deepseek-v3-2-reasoner"],
    contextWindow: 128_000,
    costInputPer1M: 0.28,
    costOutputPer1M: 0.42,
    status: "legacy",
    notes: "DeepSeek thinking/reasoning mode row; cached-input pricing excluded from display fields.",
    sourceUrls: SOURCES.deepseek,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Qwen3-Max",
    provider: "Alibaba Cloud",
    apiId: "qwen3-max",
    aliases: ["qwen3-max-latest", "qwen-3-max"],
    contextWindow: 262_144,
    costInputPer1M: 0.359,
    costOutputPer1M: 1.434,
    status: "active",
    notes: "Alibaba Cloud Model Studio global deployment row; pricing can be region-specific and tiered.",
    sourceUrls: SOURCES.qwen,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Qwen3.5 Plus",
    provider: "Alibaba Cloud",
    apiId: "qwen3.5-plus",
    aliases: ["qwen3-5-plus", "qwen-3.5-plus"],
    contextWindow: 1_000_000,
    costInputPer1M: 0.115,
    costOutputPer1M: 0.688,
    status: "active",
    notes: "Alibaba Cloud Model Studio global deployment row; pricing is tiered by request size.",
    sourceUrls: SOURCES.qwen,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Qwen3.5 Flash",
    provider: "Alibaba Cloud",
    apiId: "qwen3.5-flash",
    aliases: ["qwen3-5-flash", "qwen-3.5-flash"],
    contextWindow: 1_000_000,
    costInputPer1M: 0.029,
    costOutputPer1M: 0.287,
    status: "active",
    notes: "Alibaba Cloud Model Studio global deployment row; pricing is tiered by request size.",
    sourceUrls: SOURCES.qwen,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Qwen Plus",
    provider: "Alibaba Cloud",
    apiId: "qwen-plus",
    aliases: ["qwen-plus-latest"],
    contextWindow: 1_000_000,
    costInputPer1M: 0.115,
    costOutputPer1M: 0.287,
    status: "active",
    notes: "Qwen Plus global deployment display row.",
    sourceUrls: SOURCES.qwen,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Qwen Plus Thinking",
    provider: "Alibaba Cloud",
    apiId: "qwen-plus-thinking",
    aliases: ["qwen-plus-2025-12-01-thinking", "qwen-plus-reasoning"],
    contextWindow: 1_000_000,
    costInputPer1M: 0.115,
    costOutputPer1M: 1.147,
    status: "active",
    notes: "Qwen Plus thinking-output pricing row; output price uses the lowest global thinking tier.",
    sourceUrls: SOURCES.qwen,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Qwen Flash",
    provider: "Alibaba Cloud",
    apiId: "qwen-flash",
    aliases: ["qwen-flash-2025-07-28"],
    contextWindow: 1_000_000,
    costInputPer1M: 0.022,
    costOutputPer1M: 0.216,
    status: "active",
    notes: "Still-used lower-cost Qwen line; display price uses the lowest global tier.",
    sourceUrls: SOURCES.qwen,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Qwen Max",
    provider: "Alibaba Cloud",
    apiId: "qwen-max",
    aliases: ["qwen-max-latest", "qwen-max-2025-01-25"],
    contextWindow: 32_768,
    costInputPer1M: 0.345,
    costOutputPer1M: 1.377,
    status: "legacy",
    notes: "Legacy Qwen Max row retained for still-used integrations.",
    sourceUrls: SOURCES.qwen,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Qwen3 Coder",
    provider: "Alibaba Cloud",
    apiId: "qwen3-coder-plus",
    aliases: ["qwen3-coder", "qwen-coder"],
    contextWindow: 262_144,
    costInputPer1M: 0.115,
    costOutputPer1M: 0.688,
    status: "active",
    notes: "Qwen coder row for coding-focused comparisons; display price follows Qwen Plus global tiers.",
    sourceUrls: SOURCES.qwen,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Qwen3.5 Coder",
    provider: "Alibaba Cloud",
    apiId: "qwen3.5-coder",
    aliases: ["qwen3-5-coder"],
    contextWindow: 262_144,
    costInputPer1M: 0.115,
    costOutputPer1M: 0.688,
    status: "active",
    notes: "Qwen 3.5 coder row for coding-focused comparisons; display price follows Qwen Plus global tiers.",
    sourceUrls: SOURCES.qwen,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GLM-5.1",
    provider: "Z.AI",
    apiId: "glm-5.1",
    aliases: ["glm-5-1", "zai-glm-5.1"],
    contextWindow: 200_000,
    costInputPer1M: 1.4,
    costOutputPer1M: 4.4,
    status: "active",
    notes: "Z.AI hosted GLM 5.1 model row.",
    sourceUrls: SOURCES.zai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GLM-4.6",
    provider: "Z.AI",
    apiId: "glm-4.6",
    aliases: ["glm-4-6", "zhipu-glm-4.6"],
    contextWindow: 200_000,
    costInputPer1M: 0.6,
    costOutputPer1M: 2.2,
    status: "legacy",
    notes: "Popular GLM 4.x hosted baseline.",
    sourceUrls: SOURCES.zai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GLM-5",
    provider: "Z.AI",
    apiId: "glm-5",
    aliases: ["zai-glm-5"],
    contextWindow: 200_000,
    costInputPer1M: 1,
    costOutputPer1M: 3.2,
    status: "active",
    notes: "GLM-5 row with standard hosted pricing.",
    sourceUrls: SOURCES.zai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GLM-5 Turbo",
    provider: "Z.AI",
    apiId: "glm-5-turbo",
    aliases: ["zai-glm-5-turbo"],
    contextWindow: 200_000,
    costInputPer1M: 1.2,
    costOutputPer1M: 4,
    status: "active",
    notes: "GLM-5 Turbo pricing row; context uses the GLM 5 family context where documented.",
    sourceUrls: SOURCES.zai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GLM-4.7",
    provider: "Z.AI",
    apiId: "glm-4.7",
    aliases: ["glm-4-7", "zhipu-glm-4.7"],
    contextWindow: 200_000,
    costInputPer1M: 0.6,
    costOutputPer1M: 2.2,
    status: "legacy",
    notes: "GLM 4.7 row retained for still-used integrations.",
    sourceUrls: SOURCES.zai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GLM-4.5",
    provider: "Z.AI",
    apiId: "glm-4.5",
    aliases: ["glm-4-5", "zhipu-glm-4.5"],
    contextWindow: 128_000,
    costInputPer1M: 0.6,
    costOutputPer1M: 2.2,
    status: "legacy",
    notes: "GLM 4.5 row retained for still-used integrations.",
    sourceUrls: SOURCES.zai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GLM-4.5 Air",
    provider: "Z.AI",
    apiId: "glm-4.5-air",
    aliases: ["glm-4-5-air", "zhipu-glm-4.5-air"],
    contextWindow: 128_000,
    costInputPer1M: 0.2,
    costOutputPer1M: 1.1,
    status: "legacy",
    notes: "Lower-cost GLM 4.5 Air row retained for comparisons.",
    sourceUrls: SOURCES.zai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GLM-4-32B-0414-128K",
    provider: "Z.AI",
    apiId: "glm-4-32b-0414-128k",
    aliases: ["glm-4-32b-128k"],
    contextWindow: 128_000,
    costInputPer1M: 0.1,
    costOutputPer1M: 0.1,
    status: "legacy",
    notes: "Older GLM 4 32B row retained for still-used open-model comparisons.",
    sourceUrls: SOURCES.zai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Meta Llama 3.3 70B Versatile on Groq",
    provider: "GroqCloud",
    apiId: "llama-3.3-70b-versatile",
    aliases: [
      "meta-llama-3.3-70b-versatile",
      "llama-3-3-70b-versatile",
      "llama-3.3-70b-versatile",
    ],
    contextWindow: 131_072,
    costInputPer1M: 0.59,
    costOutputPer1M: 0.79,
    status: "hosted",
    notes: "Open-weight Meta Llama model using Groq-hosted API pricing.",
    sourceUrls: SOURCES.groq,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Meta Llama 3.1 8B Instant on Groq",
    provider: "GroqCloud",
    apiId: "llama-3.1-8b-instant",
    aliases: ["llama-3-1-8b-instant", "meta-llama-3.1-8b-instant"],
    contextWindow: 131_072,
    costInputPer1M: 0.05,
    costOutputPer1M: 0.08,
    status: "hosted",
    notes: "Groq-hosted fast Llama baseline.",
    sourceUrls: SOURCES.groq,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Meta Llama 4 Scout on Groq",
    provider: "GroqCloud",
    apiId: "llama-4-scout-17b-16e-instruct",
    aliases: ["llama-4-scout", "meta-llama-4-scout"],
    contextWindow: 131_072,
    costInputPer1M: 0.11,
    costOutputPer1M: 0.34,
    status: "hosted",
    notes: "Groq-hosted Llama 4 Scout row; hosted context and pricing can differ from Meta model-card limits.",
    sourceUrls: SOURCES.groq,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Meta Llama 4 Maverick on Groq",
    provider: "GroqCloud",
    apiId: "llama-4-maverick-17b-128e-instruct",
    aliases: ["llama-4-maverick", "meta-llama-4-maverick"],
    contextWindow: 131_072,
    costInputPer1M: 0.2,
    costOutputPer1M: 0.6,
    status: "hosted",
    notes: "Groq-hosted Llama 4 Maverick row; hosted context and pricing can differ from Meta model-card limits.",
    sourceUrls: SOURCES.groq,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Mistral Medium 3.1",
    provider: "Mistral AI",
    apiId: "mistral-medium-3.1",
    aliases: ["mistral-medium-3-1", "mistral-medium-3-1-25-08"],
    contextWindow: 128_000,
    costInputPer1M: 0.4,
    costOutputPer1M: 2,
    status: "active",
    notes: "Official Mistral Medium 3.1 model card row.",
    sourceUrls: SOURCES.mistral,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Mistral Small 3.2",
    provider: "Mistral AI",
    apiId: "mistral-small-3.2",
    aliases: ["mistral-small-3-2", "mistral-small-3-2-25-06"],
    contextWindow: 128_000,
    costInputPer1M: 0.1,
    costOutputPer1M: 0.3,
    status: "active",
    notes: "Official Mistral Small 3.2 model card row.",
    sourceUrls: SOURCES.mistral,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Ministral 3 8B",
    provider: "Mistral AI",
    apiId: "ministral-3-8b",
    aliases: ["ministral-3-8b-25-12"],
    contextWindow: 256_000,
    costInputPer1M: 0.15,
    costOutputPer1M: 0.15,
    status: "active",
    notes: "Compact Mistral family row.",
    sourceUrls: SOURCES.mistral,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Mistral Large 2",
    provider: "Mistral AI",
    apiId: "mistral-large-2407",
    aliases: ["mistral-large-2", "mistral-large"],
    contextWindow: 128_000,
    costInputPer1M: 2,
    costOutputPer1M: 6,
    status: "legacy",
    notes: "Popular older Mistral Large row retained for still-used comparisons.",
    sourceUrls: SOURCES.mistral,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Codestral",
    provider: "Mistral AI",
    apiId: "codestral-latest",
    aliases: ["codestral", "codestral-2508"],
    contextWindow: 256_000,
    costInputPer1M: 0.3,
    costOutputPer1M: 0.9,
    status: "active",
    notes: "Mistral code-specialized row retained for coding comparisons.",
    sourceUrls: SOURCES.mistral,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Command A",
    provider: "Cohere",
    apiId: "command-a",
    aliases: ["cohere-command-a"],
    contextWindow: 256_000,
    costInputPer1M: 2.5,
    costOutputPer1M: 10,
    status: "active",
    notes: "Current Cohere Command A row.",
    sourceUrls: SOURCES.cohere,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Command R+",
    provider: "Cohere",
    apiId: "command-r-plus",
    aliases: ["command-r+", "cohere-command-r-plus"],
    contextWindow: 128_000,
    costInputPer1M: 2.5,
    costOutputPer1M: 10,
    status: "legacy",
    notes: "Still-used Command R+ family baseline.",
    sourceUrls: SOURCES.cohere,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Command R",
    provider: "Cohere",
    apiId: "command-r",
    aliases: ["command-r-08-2024", "cohere-command-r"],
    contextWindow: 128_000,
    costInputPer1M: 0.15,
    costOutputPer1M: 0.6,
    status: "legacy",
    notes: "Still-used Command R baseline for RAG comparisons.",
    sourceUrls: SOURCES.cohere,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Command R7B",
    provider: "Cohere",
    apiId: "command-r7b",
    aliases: ["command-r-7b", "cohere-command-r7b"],
    contextWindow: 128_000,
    costInputPer1M: 0.0375,
    costOutputPer1M: 0.15,
    status: "active",
    notes: "Small Command R family row.",
    sourceUrls: SOURCES.cohere,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Jamba Large",
    provider: "AI21",
    apiId: "jamba-large",
    aliases: ["ai21-jamba-large", "jamba-1.5-large"],
    contextWindow: 256_000,
    costInputPer1M: 2,
    costOutputPer1M: 8,
    status: "active",
    notes: "AI21 Jamba foundation model row.",
    sourceUrls: SOURCES.ai21,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Jamba Mini",
    provider: "AI21",
    apiId: "jamba-mini",
    aliases: ["ai21-jamba-mini", "jamba-1.5-mini"],
    contextWindow: 256_000,
    costInputPer1M: 0.2,
    costOutputPer1M: 0.4,
    status: "active",
    notes: "Lower-cost AI21 Jamba row.",
    sourceUrls: SOURCES.ai21,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GPT-5.5",
    provider: "OpenAI",
    apiId: "gpt-5.5",
    aliases: ["gpt-5-5"],
    contextWindow: 1_000_000,
    costInputPer1M: 5,
    costOutputPer1M: 30,
    status: "active",
    notes: "OpenAI flagship model row with standard processing pricing.",
    sourceUrls: SOURCES.openai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GPT-5.4",
    provider: "OpenAI",
    apiId: "gpt-5.4",
    aliases: ["gpt-5-4"],
    contextWindow: 1_000_000,
    costInputPer1M: 2.5,
    costOutputPer1M: 15,
    status: "active",
    notes: "OpenAI lower-cost frontier row with standard processing pricing.",
    sourceUrls: SOURCES.openai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GPT-5.4 mini",
    provider: "OpenAI",
    apiId: "gpt-5.4-mini",
    aliases: ["gpt-5-4-mini"],
    contextWindow: 400_000,
    costInputPer1M: 0.75,
    costOutputPer1M: 4.5,
    status: "active",
    notes: "OpenAI mini frontier row with standard processing pricing.",
    sourceUrls: SOURCES.openai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GPT-5.4 nano",
    provider: "OpenAI",
    apiId: "gpt-5.4-nano",
    aliases: ["gpt-5-4-nano"],
    contextWindow: 400_000,
    costInputPer1M: 0.1,
    costOutputPer1M: 0.6,
    status: "active",
    notes: "OpenAI nano row for very low-cost comparisons.",
    sourceUrls: SOURCES.openai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "o3",
    provider: "OpenAI",
    apiId: "o3",
    aliases: ["openai-o3"],
    contextWindow: 200_000,
    costInputPer1M: 2,
    costOutputPer1M: 8,
    status: "legacy",
    notes: "OpenAI reasoning model row for thinking-heavy comparisons.",
    sourceUrls: SOURCES.openai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "o4-mini",
    provider: "OpenAI",
    apiId: "o4-mini",
    aliases: ["openai-o4-mini"],
    contextWindow: 200_000,
    costInputPer1M: 1.1,
    costOutputPer1M: 4.4,
    status: "legacy",
    notes: "OpenAI smaller reasoning model row for thinking-heavy comparisons.",
    sourceUrls: SOURCES.openai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "o3-mini",
    provider: "OpenAI",
    apiId: "o3-mini",
    aliases: ["openai-o3-mini"],
    contextWindow: 200_000,
    costInputPer1M: 1.1,
    costOutputPer1M: 4.4,
    status: "legacy",
    notes: "Older OpenAI mini reasoning row retained for comparison.",
    sourceUrls: SOURCES.openai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GPT-4.1",
    provider: "OpenAI",
    apiId: "gpt-4.1",
    aliases: ["gpt-4-1"],
    contextWindow: 1_000_000,
    costInputPer1M: 2,
    costOutputPer1M: 8,
    status: "active",
    notes: "Long-context OpenAI GPT-4.1 row.",
    sourceUrls: SOURCES.openai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GPT-4o",
    provider: "OpenAI",
    apiId: "gpt-4o",
    aliases: ["gpt-4o-2024-08-06", "openai-gpt-4o"],
    contextWindow: 128_000,
    costInputPer1M: 2.5,
    costOutputPer1M: 10,
    status: "legacy",
    notes: "Popular multimodal baseline retained for benchmark and comparison coverage.",
    sourceUrls: SOURCES.openai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "GPT-4o mini",
    provider: "OpenAI",
    apiId: "gpt-4o-mini",
    aliases: ["gpt-4o-mini-2024-07-18"],
    contextWindow: 128_000,
    costInputPer1M: 0.15,
    costOutputPer1M: 0.6,
    status: "legacy",
    notes: "Low-cost OpenAI baseline.",
    sourceUrls: SOURCES.openai,
    lastVerified: LAST_VERIFIED,
  },
  {
    name: "Grok 4.3",
    provider: "xAI",
    apiId: "grok-4.3",
    aliases: ["xai-grok-4.3"],
    contextWindow: 1_000_000,
    costInputPer1M: 1.25,
    costOutputPer1M: 2.5,
    status: "active",
    notes: "xAI Grok row; tools and add-on billing are excluded from display token prices.",
    sourceUrls: SOURCES.xai,
    lastVerified: LAST_VERIFIED,
  },
] as const satisfies readonly CuratedModel[];

function normalizeLookupKey(value: string): string {
  return value.trim().toLocaleLowerCase();
}

function sortByProviderThenName<T extends { provider: string; name: string }>(
  left: T,
  right: T,
): number {
  return (
    left.provider.localeCompare(right.provider) ||
    left.name.localeCompare(right.name)
  );
}

export function listCatalogModels(): CuratedModel[] {
  return [...CURATED_MODEL_CATALOG].sort(sortByProviderThenName);
}

export function findCatalogModel(name: string): CuratedModel | undefined {
  const lookupName = normalizeLookupKey(name);

  if (!lookupName) {
    return undefined;
  }

  return CURATED_MODEL_CATALOG.find((model) => {
    const identifiers = [model.name, model.apiId, ...model.aliases].filter(
      Boolean,
    ) as string[];

    return identifiers.some(
      (identifier) => normalizeLookupKey(identifier) === lookupName,
    );
  });
}

export function applyCatalogMetadata<T extends BenchmarkMetadataRecord>(
  record: T,
): T {
  const catalogModel = findCatalogModel(record.modelName);

  if (!catalogModel) {
    return { ...record };
  }

  return {
    ...record,
    modelName: catalogModel.name,
    provider: catalogModel.provider,
    contextWindow:
      record.contextWindow ?? catalogModel.contextWindow ?? null,
    costInputPer1M:
      record.costInputPer1M ?? catalogModel.costInputPer1M ?? null,
    costOutputPer1M:
      record.costOutputPer1M ?? catalogModel.costOutputPer1M ?? null,
  };
}

export function mergeCatalogWithDbModels(
  dbModels: readonly DbCatalogModel[],
): CatalogModelOption[] {
  const optionsByLookupName = new Map<string, CatalogModelOption>();

  for (const dbModel of dbModels) {
    const catalogModel = findCatalogModel(dbModel.name);
    const hasBenchmarks = (dbModel.scores?.length ?? 0) > 0;

    if (
      !catalogModel &&
      (!hasBenchmarks || !isDisplayableModelName(dbModel.name))
    ) {
      continue;
    }

    const option: CatalogModelOption = {
      name: dbModel.name,
      provider: dbModel.provider || catalogModel?.provider || "Unknown",
      contextWindow:
        dbModel.contextWindow ?? catalogModel?.contextWindow ?? null,
      costInputPer1M:
        dbModel.costInputPer1M ?? catalogModel?.costInputPer1M ?? null,
      costOutputPer1M:
        dbModel.costOutputPer1M ?? catalogModel?.costOutputPer1M ?? null,
      hasBenchmarks,
      status: hasBenchmarks ? "benchmarked" : (catalogModel?.status ?? "active"),
      sourceUrls: catalogModel?.sourceUrls,
      lastVerified: catalogModel?.lastVerified,
    };

    optionsByLookupName.set(normalizeLookupKey(dbModel.name), option);

    if (catalogModel) {
      optionsByLookupName.set(normalizeLookupKey(catalogModel.name), option);
    }
  }

  for (const catalogModel of CURATED_MODEL_CATALOG) {
    const lookupName = normalizeLookupKey(catalogModel.name);

    if (optionsByLookupName.has(lookupName)) {
      continue;
    }

    optionsByLookupName.set(lookupName, {
      name: catalogModel.name,
      provider: catalogModel.provider,
      contextWindow: catalogModel.contextWindow,
      costInputPer1M: catalogModel.costInputPer1M,
      costOutputPer1M: catalogModel.costOutputPer1M,
      hasBenchmarks: false,
      status: catalogModel.status,
      sourceUrls: catalogModel.sourceUrls,
      lastVerified: catalogModel.lastVerified,
    });
  }

  return Array.from(new Set(optionsByLookupName.values())).sort(
    sortByProviderThenName,
  );
}

export function isDisplayableModelName(name: string) {
  return !/^https?:\/\//i.test(name.trim());
}
